#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Missing argument (commit message). Did you try to run this manually?"
	exit 1
fi

commitTitle="$(cat $1 | head -n1)"

# ignore merge requests
if echo "$commitTitle" | grep -qE "^Merge branch"; then
	echo "Commit hook: ignoring branch merge"
	exit 0
fi

# check commit message
REGEX='^(feat|fix|docs|style|refactor|ci|test|chore|comment)\(.*\)\:.*'
if ! echo "$commitTitle" | grep -qE ${REGEX}; then
	echo "Your commit title '$commitTitle' did not follow conventional commit message rules:"
	echo "Please comply with the regex ${REGEX}"
	echo "See https://karma-runner.github.io/6.3/dev/git-commit-msg.html for more information on conventional commits"
	exit 1
fi
