<?php
/**
 * CrowdSec_Bouncer Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Bouncer
 * @copyright  Copyright (c)  2021+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Bouncer
 * @module   Bouncer
 * @author   CrowdSec team
 *
 */
/**
 *
 * @phpcs:disable Magento2.Legacy.EscapeMethodsOnBlockClass
 *
 */
?>

<?php
/** @var \CrowdSec\Bouncer\Block\Adminhtml\System\Config\Connection\Ping $block */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function pingConnection() {
            var pingConnectionMessage = $('lapi_ping_result');

            params = {
                api_url: $('<?= $block->escapeJs($block->getUrlField()) ?>').value,
                bouncer_key: $('<?= $block->escapeJs($block->getKeyField()) ?>').value,
                auth_type: $('<?= $block->escapeJs($block->getAuthTypeField()) ?>').value,
                tls_cert_path: $('<?= $block->escapeJs($block->getTlsCertPathField()) ?>').value,
                tls_key_path: $('<?= $block->escapeJs($block->getTlsKeyPathField()) ?>').value,
                tls_verify_peer: $('<?= $block->escapeJs($block->getTlsVerifyPeerField()) ?>').value,
                tls_ca_cert_path: $('<?= $block->escapeJs($block->getTlsCaCertPathField()) ?>').value,
                use_curl: $('<?= $block->escapeJs($block->getUseCurlField()) ?>').value,
                api_connect: $('<?= $block->escapeJs($block->getApiTimeoutField()) ?>').value,
                api_connect_timeout: $('<?= $block->escapeJs($block->getApiConnectTimeoutField()) ?>').value
            };

            new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
                parameters: params,
                onSuccess: function(response) {
                    var result =
                        '<?= $block->escapeJs($block->escapeHtml(__('Error during CrowdSec Connection ping.'))) ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.connection == 1) {
                            pingConnectionMessage.removeClassName('hidden')
                                .removeClassName('error').addClassName('success');
                        } else {
                            pingConnectionMessage.removeClassName('hidden').removeClassName('success')
                                .addClassName('error');
                        }
                    } catch (e) {
                        pingConnectionMessage.removeClassName('hidden').removeClassName('success')
                            .addClassName('error');
                    }
                    pingConnectionMessage.update(result);
                }
            });
        }

        window.pingConnection = pingConnection;
//]]>

    });
</script>

<div class="actions actions-ping-connection actions-crowdsec">
    <button onclick="javascript:pingConnection(); return false;" class="action-ping-connection" type="button" id="<?=
    $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="hidden" id="lapi_ping_result"></p>
</div>
