<?php
/**
 * Crowdsec_Bouncer Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   Crowdsec
 * @package    Crowdsec_Bouncer
 * @copyright  Copyright (c)  2021+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category Crowdsec
 * @package  Crowdsec_Bouncer
 * @module   Bouncer
 * @author   CrowdSec team
 *
 */

/** @var \Crowdsec\Bouncer\Block\Adminhtml\System\Config\Connection\Ping $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/**  @var \Magento\Framework\Escaper $escaper */
?>

<?php

$ajaxUrl = $escaper->escapeJs($block->getAjaxUrl());
$errorMessage = $escaper->escapeJs($escaper->escapeHtml(__('Error during Crowdsec Connection ping.')));
$urlField = $escaper->escapeJs($block->getUrlField());
$keyField = $escaper->escapeJs($block->getKeyField());

 $scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function pingConnection() {
        var pingConnectionMessage = $('cache_ping_result');

        params = {
            api_url: $('{$urlField}').value,
            bouncer_key: $('{$keyField}').value
        };

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.connection == 1) {
                        pingConnectionMessage.removeClassName('hidden').removeClassName('admin__field-error').
                        addClassName('note');
                        pingConnectionMessage.setStyle(
                            {
                                color:'green',
                                border:'1px solid #ee7d7d',
                                padding:'.8rem 1rem .9rem'
                             }
                        );
                    } else {
                        pingConnectionMessage.removeClassName('hidden').addClassName('admin__field-error');
                    }
                } catch (e) {
                    pingConnectionMessage.removeClassName('hidden').addClassName('admin__field-error');
                }
                pingConnectionMessage.update(result);
            }
        });
    }

    window.pingConnection = pingConnection;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-ping-connection">
    <button class="action-ping-connection" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="admin__field-error hidden" id="cache_ping_result"></p>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#cache_ping_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'pingConnection();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
