<?php
/**
 * CrowdSec_Bouncer Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Bouncer
 * @copyright  Copyright (c)  2021+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Bouncer
 * @module   Bouncer
 * @author   CrowdSec team
 *
 */

/** @var \CrowdSec\Bouncer\Block\Adminhtml\System\Config\Connection\Ping $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/**  @var \Magento\Framework\Escaper $escaper */
?>

<?php

$ajaxUrl = $escaper->escapeJs($block->getAjaxUrl());
$errorMessage = $escaper->escapeJs($escaper->escapeHtml(__('Error during CrowdSec Connection ping.')));
$urlField = $escaper->escapeJs($block->getUrlField());
$keyField = $escaper->escapeJs($block->getKeyField());
$useCurlField = $escaper->escapeJs($block->getUseCurlField());

 $scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function pingConnection() {
        var pingConnectionMessage = $('lapi_ping_result');

        params = {
            api_url: $('{$urlField}').value,
            bouncer_key: $('{$keyField}').value,
            use_curl: $('{$useCurlField}').value
        };

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.connection == 1) {
                        pingConnectionMessage.removeClassName('hidden')
                                .removeClassName('error').addClassName('success');
                    } else {
                        pingConnectionMessage.removeClassName('hidden').removeClassName('success')
                                .addClassName('error');
                    }
                } catch (e) {
                    pingConnectionMessage.removeClassName('hidden').removeClassName('success')
                            .addClassName('error');
                }
                pingConnectionMessage.update(result);
            }
        });
    }

    window.pingConnection = pingConnection;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-ping-connection actions-crowdsec">
    <button class="action-ping-connection" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="hidden" id="lapi_ping_result"></p>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#lapi_ping_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'pingConnection();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
