<?php
/**
 * Crowdsec_Bouncer Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   Crowdsec
 * @package    Crowdsec_Bouncer
 * @copyright  Copyright (c)  2021+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category Crowdsec
 * @package  Crowdsec_Bouncer
 * @module   Bouncer
 * @author   CrowdSec team
 *
 */

?>

<?php
/** @var \Crowdsec\Bouncer\Block\Adminhtml\System\Config\Cache\Clear $block */
?>
<script>
    require(['prototype'], function(){

//<![CDATA[
        function clearCache() {
            var clearCacheMessage = $('cache_clearing_result');

            params = {};

            new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
                parameters: params,
                onSuccess: function(response) {
                    var result =
                        '<?= $block->escapeJs($block->escapeHtml(__('Error during Crowdsec Cache clearing.'))) ?>';
                    try {
                        if (response.responseText.isJSON()) {
                            response = response.responseText.evalJSON();
                            result = response.message;
                        }
                        if (response.cleared == 1) {
                            clearCacheMessage.removeClassName('hidden').removeClassName('admin__field-error').
                            addClassName('note');
                            clearCacheMessage.setStyle(
                                {
                                    color:'green',
                                    border:'1px solid #ee7d7d',
                                    padding:'.8rem 1rem .9rem'
                                }
                            );
                        } else {
                            clearCacheMessage.removeClassName('hidden').addClassName('admin__field-error');
                        }
                    } catch (e) {
                        clearCacheMessage.removeClassName('hidden').addClassName('admin__field-error');
                    }
                    clearCacheMessage.update(result);
                }
            });
        }

        window.clearCache = clearCache;
//]]>

    });
</script>

<div class="actions actions-clear-cache">
    <button onclick="javascript:clearCache(); return false;" class="action-clear-cache" type="button" id="<?=
    $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="admin__field-error hidden" id="cache_clearing_result"></p>
</div>

