<?php
/**
 * CrowdSec_Bouncer Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Bouncer
 * @copyright  Copyright (c)  2021+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Bouncer
 * @module   Bouncer
 * @author   CrowdSec team
 *
 */

/** @var \CrowdSec\Bouncer\Block\Adminhtml\System\Config\Cache\Prune $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/**  @var \Magento\Framework\Escaper $escaper */
?>

<?php

 $ajaxUrl = $escaper->escapeJs($block->getAjaxUrl());
 $errorMessage = $escaper->escapeJs($escaper->escapeHtml(__('Error during CrowdSec Cache pruning.')));

 $scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function pruneCache() {
        var pruneCacheMessage = $('cache_pruning_result');

        params = {};

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.pruned == 1) {
                        pruneCacheMessage.removeClassName('hidden').removeClassName('admin__field-error').
                        addClassName('note');
                        pruneCacheMessage.setStyle(
                            {
                                color:'green',
                                border:'1px solid #ee7d7d',
                                padding:'.8rem 1rem .9rem'
                             }
                        );
                    } else {
                        pruneCacheMessage.removeClassName('hidden').addClassName('admin__field-error');
                    }
                } catch (e) {
                    pruneCacheMessage.removeClassName('hidden').addClassName('admin__field-error');
                }
                pruneCacheMessage.update(result);
            }
        });
    }

    window.pruneCache = pruneCache;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-prune-cache">
    <button class="action-prune-cache" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="admin__field-error hidden" id="cache_pruning_result"></p>
    <p class="note">
        <span><?= $escaper->escapeHtml(
            __('Cache pruning is the process whereby entries that have expired are removed from the cache.
        Unlike Redis and Memcached, File system cache has no auto-purge mechanism.')
        ) ?></span>
    </p>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#cache_pruning_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'pruneCache();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
