<?php
/**
 * CrowdSec_Bouncer Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT LICENSE
 * that is bundled with this package in the file LICENSE
 *
 * @category   CrowdSec
 * @package    CrowdSec_Bouncer
 * @copyright  Copyright (c)  2021+ CrowdSec
 * @author     CrowdSec team
 * @see        https://crowdsec.net CrowdSec Official Website
 * @license    MIT LICENSE
 *
 */

/**
 *
 * @category CrowdSec
 * @package  CrowdSec_Bouncer
 * @module   Bouncer
 * @author   CrowdSec team
 *
 */

/** @var \CrowdSec\Bouncer\Block\Adminhtml\System\Config\Cache\Refresh $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/**  @var \Magento\Framework\Escaper $escaper */
?>

<?php

 $ajaxUrl = $escaper->escapeJs($block->getAjaxUrl());
 $errorMessage = $escaper->escapeJs($escaper->escapeHtml(__('Error during CrowdSec Cache refresh.')));

 $scriptString = <<<script
require(['prototype'], function(){

//<![CDATA[
    function refreshCache() {
        var refreshCacheMessage = $('cache_refresh_result');

        params = {};

        new Ajax.Request('{$ajaxUrl}', {
            parameters: params,
            onSuccess: function(response) {
                var result = '{$errorMessage}';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.refresh == 1) {
                        refreshCacheMessage.removeClassName('hidden')
                                .removeClassName('error').addClassName('success');
                    } else {
                        refreshCacheMessage.removeClassName('hidden').removeClassName('success')
                                .addClassName('error');
                    }
                } catch (e) {
                    refreshCacheMessage.removeClassName('hidden').removeClassName('success')
                            .addClassName('error');
                }
                refreshCacheMessage.update(result);
            }
        });
    }

    window.refreshCache = refreshCache;
//]]>

});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>

<div class="actions actions-refresh-cache actions-crowdsec">
    <button class="action-refresh-cache" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <p class="hidden" id="cache_refresh_result"></p>
</div>
<?= /* @noEscape */ $secureRenderer->renderTag('style', [], '#cache_refresh_result {margin-bottom: 10px;}', false); ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    'refreshCache();event.preventDefault();',
    '#' . /* @noEscape */ $block->getHtmlId()
); ?>
