name: End-to-end release tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '25 08 * * *'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        default: false
      check_head_zip:
        type: boolean
        description: Use expected ZIP on HEAD sources
        default: false

permissions:
  contents: read

jobs:
  end-to-end-test-suite:
    strategy:
      fail-fast: false
      matrix:
        # Last 2 patches for the current minor, and last patch for the previous minor, greatest php version
        include:
          - m2-version: '2.3.7'
            php-version: '7.4'
          - m2-version: '2.4.4'
            php-version: '8.1'
          - m2-version: '2.4.5'
            php-version: '8.1'

    name: End-to-end test suite
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    runs-on: ubuntu-latest
    env:
      EXTENSION_PACKAGE_NAME: "crowdsec/magento2-module-bouncer"
      EXTENSION_NAME: "CrowdSec_Bouncer"
      EXTENSION_PATH: "crowdsec-bouncer"
      ORIGIN: "https://github.com/crowdsecurity/cs-magento-bouncer"

    steps:

      - name: Install Magento 2 with DDEV
        uses: julienloizelet/github-actions-magento2-ddev-installation@v1.4.0
        with:
          php_version: ${{ matrix.php-version }}
          magento_version: ${{ matrix.m2-version }}
          composer_auth: ${{ secrets.M2_COMPOSER_AUTH }}
          magento_repository: "https://repo.magento.com/"

      - name: Add Crowdsec and Playwright to DDEV
        run: |
          cp .ddev/additional_docker_compose/docker-compose.playwright-alone.yaml .ddev/docker-compose.playwright.yaml
          cp .ddev/additional_docker_compose/docker-compose.crowdsec.yaml .ddev/docker-compose.crowdsec.yaml
          cp .ddev/custom_files/varnish-profile.xml varnish-profile.xml
          ddev restart

      - name: Clone M2 ${{ env.EXTENSION_NAME }} files
        uses: actions/checkout@v3
        with:
          path: module-sources

      - name: Use zip sources as for a release process
        if: github.event_name == 'push' || github.event.inputs.check_head_zip == 'true'
        run: |
          zip -r crowdsec-head.zip module-sources/ -x 'module-sources/.git*'
          mkdir temp-dir
          unzip crowdsec-head.zip -d temp-dir
          mkdir -p ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}
          cd temp-dir/module-sources
          cp -r . ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}
          ls -al ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}

      - name: Retrieve last stable release zip
        if: github.event_name != 'push' && github.event.inputs.check_head_zip != 'true'
        run: |
          LAST_TAG=$(curl -Ls -o /dev/null -w %{url_effective} ${{ env.ORIGIN }}/releases/latest | grep -oP "\/tag\/v\K(.*)$")
          curl -fL ${{ env.ORIGIN }}/releases/download/v$LAST_TAG/crowdsec-magento2-module-bouncer-$LAST_TAG.zip -o crowdsec.$LAST_TAG.zip
          mkdir release-sources
          unzip crowdsec.$LAST_TAG.zip -d release-sources
          mkdir -p ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}
          cd release-sources/crowdsec-magento2-module-bouncer-$LAST_TAG
          cp -r . ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}
          ls -al ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}

      - name: Validate composer.json
        run: ddev composer validate --working-dir ./my-own-modules/${{ env.EXTENSION_PATH }}

      - name: Prepare composer repositories
        run: |
          ddev composer config --unset repositories.0
          ddev composer config repositories.0 '{"type": "path", "url":"my-own-modules/${{ env.EXTENSION_PATH }}/",  "canonical": true}'
          ddev composer config repositories.1 '{"type": "composer", "url":"https://repo.magento.com/",  "exclude": ["${{ env.EXTENSION_PACKAGE_NAME }}"]}'

      - name: Add ${{ env.EXTENSION_NAME }} as composer dependency
        run: |
          ddev composer require ${{ env.EXTENSION_PACKAGE_NAME }}:@dev --no-interaction

      - name: Disable some extensions for 2.4
        if: startsWith(matrix.m2-version, '2.4')
        run: |
          ddev magento module:disable Magento_TwoFactorAuth
          ddev magento module:disable Magento_AdminNotification

      - name: Make some workaround for 2.3.5
        if: startsWith(matrix.m2-version, '2.3.5')
        run: |
          ddev magento  module:disable Dotdigitalgroup_Chat
          ddev magento  module:disable Dotdigitalgroup_Email

      - name: Enable extension
        run: |
          ddev magento deploy:mode:set developer
          ddev magento module:enable ${{ env.EXTENSION_NAME }}
          ddev magento setup:upgrade
          ddev magento setup:static-content:deploy -f
          ddev crowdsec-config
          ddev magento cache:flush

      - name: Prepare for playwright test
        run: |
          ddev magento setup:performance:generate-fixtures ./varnish-profile.xml
          ddev magento cache:flush
          mkdir -p var/crowdsec/tls
          cp -r .ddev/custom_files/crowdsec/cfssl/* var/crowdsec/tls
          ddev maxmind-download DEFAULT GeoLite2-City /var/www/html/var/crowdsec
          ddev maxmind-download DEFAULT GeoLite2-Country /var/www/html/var/crowdsec
          cd var/crowdsec
          sha256sum -c GeoLite2-Country.tar.gz.sha256.txt
          sha256sum -c GeoLite2-City.tar.gz.sha256.txt
          tar -xf GeoLite2-Country.tar.gz
          tar -xf GeoLite2-City.tar.gz
          rm GeoLite2-Country.tar.gz GeoLite2-Country.tar.gz.sha256.txt GeoLite2-City.tar.gz GeoLite2-City.tar.gz.sha256.txt
          cd ${{ github.workspace }}
          cp .ddev/custom_scripts/cronLaunch.php ${{ github.workspace }}/pub/cronLaunch.php
          cp .ddev/custom_scripts/cacheActions.php ${{ github.workspace }}/pub/cacheActions.php
          cd ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd/__scripts__
          chmod +x test-init.sh
          ./test-init.sh
          chmod +x run-tests.sh
          cd ${{ github.workspace }}/module-sources
          cp -r .github ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}
          ls -al ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}

      - name: Run config test
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 1-config.js

      - name: Run live mode test
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 2-live-mode.js

      - name: Run stream mode test
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 3-stream-mode.js

      - name: Run cron test
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 4-cron.js

      - name: Run api tests
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 5-api.js

      - name: Run events logging test
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 6-events.js

      - name: Run geolocation test
        uses: ./my-own-modules/crowdsec-bouncer/.github/workflows/end-to-end/run-single-test
        with:
          test_path: ${{ github.workspace }}/my-own-modules/${{ env.EXTENSION_PATH }}/Test/EndToEnd
          file_path: 7-geolocation.js

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 30
        if: failure() && github.event.inputs.debug_enabled == 'true'

