name: Static and unit test suite
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  static-and-unit-test-suite:
    strategy:
      fail-fast: false
      matrix:
        m2-version: [ "2.3.0", "2.4.0", "2.4.3" ]
        php-version: ["7.2", "7.3", "7.4"]
        exclude:
          - { php-version: "7.4", m2-version: "2.3.0"}
          - { php-version: "7.3", m2-version: "2.3.0"}
          - { php-version: "7.2", m2-version: "2.4.3"}
          - { php-version: "7.2", m2-version: "2.4.0"}
          - { php-version: "7.3", m2-version: "2.4.0"}

    name: Static and unit test suite
    runs-on: ubuntu-latest
    env:
      EXTENSION_PACKAGE_NAME: "crowdsec/magento2-module-bouncer"
      EXTENSION_NAME: "CrowdSec_Bouncer"
      EXTENSION_PATH: "crowdsec-bouncer"

    steps:
      - name: Clone DDEV files
        uses: actions/checkout@v2
        with:
          path: .ddev
          repository: julienloizelet/ddev-m2

      - name: Install DDEV
        env:
          DDEV_VERSION: v1.19.1
        run: |
          # @see https://ddev.readthedocs.io/en/stable/#installationupgrade-script-linux-and-macos-armarm64-and-amd64-architectures
          sudo apt-get -qq update
          sudo apt-get -qq -y install libnss3-tools
          curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh
          bash install_ddev.sh ${{env.DDEV_VERSION}}
          ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
          rm install_ddev.sh

      - name: Set M2_VERSION_CODE env
        # used in some directory path and conventional file naming
        # Example : 2.4.2 => m242
        run: |
           echo "M2_VERSION_CODE=$(echo m${{ matrix.m2-version }} | sed 's/\.//g' )" >> $GITHUB_ENV

      - name: Set ELASTIC_INSTALL_STRING env for 2.4
        if: startsWith(matrix.m2-version, '2.4')
        run: echo "ELASTIC_INSTALL_STRING='--elasticsearch-host=elasticsearch'" >> $GITHUB_ENV

      - name: Start DDEV for ${{ matrix.m2-version }} with PHP ${{ matrix.php-version }}
        run: |
          cp .ddev/config_overrides/config.${{ env.M2_VERSION_CODE }}.yaml .ddev/config.${{ env.M2_VERSION_CODE }}.yaml
          cp .ddev/additional_docker_compose/docker-compose.crowdsec.yaml .ddev/docker-compose.crowdsec.yaml
          sed -i -e 's/^php_version:.*/php_version: ${{ matrix.php-version }}/g' .ddev/config.${{ env.M2_VERSION_CODE }}.yaml
          ddev start

      - name: Set COMPOSER_VERSION env
        run: |
          echo "COMPOSER_VERSION=$(ddev composer -- --version | grep -oE "([0-9]{1,}\.)([0-9]{1,}\.)([0-9]{1,})(-(alpha|beta)\.[0-9]{1,})?" | head -1)" >> $GITHUB_ENV

      - name: Install Magento ${{ matrix.m2-version }} with PHP ${{ matrix.php-version }}
        # We don't use "ddev composer" create as it restarts all containers
        run: |
          ddev composer config --global http-basic.repo.magento.com ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }} ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
          ddev exec composer create --repository=https://repo.magento.com/ magento/project-community-edition ${{ env.M2_VERSION_CODE }} ${{ matrix.m2-version }}
          cp -r ${{ env.M2_VERSION_CODE }}/. ${{ github.workspace }}
          rm -rf ${{ env.M2_VERSION_CODE }}

      - name: Setup Magento ${{ matrix.m2-version }} with PHP ${{ matrix.php-version }}
        run: |
          ddev magento setup:install \
                           --base-url=https://${{ env.M2_VERSION_CODE }}.ddev.site \
                           --db-host=db \
                           --db-name=db \
                           --db-user=db \
                           --db-password=db \
                           --backend-frontname=admin \
                           --admin-firstname=admin \
                           --admin-lastname=admin \
                           --admin-email=admin@admin.com \
                           --admin-user=admin \
                           --admin-password=admin123 \
                           --language=en_US \
                           --currency=USD \
                           --timezone=America/Chicago \
                           --use-rewrites=1 \
                           ${{ env.ELASTIC_INSTALL_STRING }}

      - name: Clone M2 Crowdsec Bouncer files
        uses: actions/checkout@v2
        with:
          path: my-own-modules/crowdsec-bouncer

      - name: Prepare composer repositories
        run: |
          ddev composer config --unset repositories.0
          ddev composer config repositories.0 '{"type": "path", "url":"my-own-modules/${{ env.EXTENSION_PATH }}/",  "canonical": true}'
          ddev composer config repositories.1 '{"type": "composer", "url":"https://repo.magento.com/",  "exclude": ["${{ env.EXTENSION_PACKAGE_NAME }}"]}'
          cat composer.json

      - name: Add ${{ env.EXTENSION_NAME }} as composer dependency
        run: |
          ddev composer require ${{ env.EXTENSION_PACKAGE_NAME }}:@dev --no-interaction

      - name: Add Coding Standard and PHPStan for Magento 2.3
        if: startsWith(matrix.m2-version, '2.3')
        run: |
          ddev composer require squizlabs/php_codesniffer:^3.4 magento/magento-coding-standard
          ddev exec vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/
          ddev composer require --dev phpstan/phpstan:0.12.23 bitexpert/phpstan-magento:v0.10.0
          mkdir dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan
          cp .ddev/custom_files/phpstan.neon dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon

      - name: PHP CODE SNIFFER
        run: |
          ddev phpcs vendor/${{ env.EXTENSION_PACKAGE_NAME }}

      - name: PHP MESS DETECTOR
        run: |
          ddev phpmd vendor/${{ env.EXTENSION_PACKAGE_NAME }}

      - name: PHPSTAN
        run: |
          ddev phpstan vendor/${{ env.EXTENSION_PACKAGE_NAME }}

      - name: PHP UNIT
        run: |
          ddev phpunit vendor/${{ env.EXTENSION_PACKAGE_NAME }}/Test/Unit



